project_id = "lcrayouskoctmbecomoi"

[functions.fetch-syslog]
verify_jwt = false

[functions.import-syslog]
verify_jwt = false

[functions.lookup-callsign]
verify_jwt = false

[functions.aggregate-syslog]
verify_jwt = false

[functions.analyze-dashboard]
verify_jwt = false

[functions.submit-support]
verify_jwt = false

[functions.inactive-hubs]
verify_jwt = false